/* eslint-disable */
/* auto-generated by subtrack build */

import { createRequire } from "node:module"

const require = createRequire(import.meta.url)
const nativeBinding = require("./index.cjs")
export const {
  Database,
  // Types are re-exported for convenience; they are interfaces only in TS.
  // In JS/TS runtime, only Database class is meaningful.
} = nativeBinding
export default nativeBinding
