/* ─── Auto-generated by napi + manual maintenance ─── */

export interface Subscription {
  id: number
  name: string
  price: number
  currency: string
  cycle: string
  status: string
  billingDay: number | null
  createdAt: string
  notes: string | null
  paymentMethod: string | null
  contractStart: string | null
  contractEnd: string | null
  autoRenewal: boolean
  vendorName: string | null
  vendorUrl: string | null
  planTier: string | null
  discountAmount: number | null
  discountType: string | null
  tags: string[]
}

export interface NewSubscriptionInput {
  name: string
  price: number
  currency: string
  cycle: string
  status?: string
  billingDay?: number | null
  notes?: string | null
  paymentMethod?: string | null
  contractStart?: string | null
  contractEnd?: string | null
  autoRenewal?: boolean
  vendorName?: string | null
  vendorUrl?: string | null
  planTier?: string | null
  discountAmount?: number | null
  discountType?: string | null
  tags?: string[]
}

export interface UpdateSubscriptionInput {
  name?: string
  price?: number
  currency?: string
  cycle?: string
  status?: string
  billingDay?: number | null
  notes?: string | null
  paymentMethod?: string | null
  contractStart?: string | null
  contractEnd?: string | null
  autoRenewal?: boolean
  vendorName?: string | null
  vendorUrl?: string | null
  planTier?: string | null
  discountAmount?: number | null
  discountType?: string | null
  tags?: string[]
}

export interface Tag {
  id: number
  name: string
  subs_count: number
}

export interface LlmUsageEntry {
  id: number
  provider: string
  model: string
  input_tokens: number
  output_tokens: number
  cost: number
  date: string
  description: string | null
  generation_id: string | null
}

export interface NewLlmUsageInput {
  provider: string
  model: string
  input_tokens: number
  output_tokens: number
  cost: number
  date: string
  description?: string | null
  generation_id?: string | null
}

export interface UsageFilter {
  provider?: string | null
  from?: string | null
  to?: string | null
  limit?: number
  offset?: number
  minCost?: number | null
}

export interface UsageTotal {
  total: number
  count: number
}

export interface UsageByProvider {
  provider: string
  total: number
  count: number
}

export interface BatchUsageResult {
  added: number
  skipped: number
}

export interface TrialEntry {
  id: number
  name: string
  expires_at: string
  price: number | null
  currency: string | null
  cycle: string | null
  notes: string | null
  created_at: string
}

export interface NewTrialInput {
  name: string
  expires_at: string
  price?: number | null
  currency?: string | null
  cycle?: string | null
  notes?: string | null
}

export interface BackupFileInfo {
  name: string
  path: string
  size: number
  created_at: string
}

export interface PriceHistoryEntry {
  id: number
  subscription_id: number
  price: number
  currency: string
  cycle: string
  changed_at: string
}

export interface AuditEntry {
  id: number
  subscription_id: number | null
  action: string
  field: string | null
  old_value: string | null
  new_value: string | null
  timestamp: string
}

export interface DatabaseStats {
  total_subscriptions: number
  active_subscriptions: number
  monthly_total: number
  yearly_total: number
  most_expensive: Subscription | null
  currency_breakdown: Record<string, number>
  tag_count: number
}

export interface BulkFilter {
  tag?: string | null
  status?: string | null
  cycle?: string | null
  priceMin?: number | null
  priceMax?: number | null
  currency?: string | null
  planTier?: string | null
}

export interface MaintenanceResult {
  issues_found: number
  issues_fixed: number
  details: string[]
}

export interface OptimizeResult {
  recommendations: number
  details: string[]
}

export interface ExportOptions {
  format: string
  filePath: string
}

export interface ImportResult {
  imported: number
  skipped: number
  errors: string[]
}

export interface ConfigData {
  default_currency: string
  theme: string
  reminders: boolean
  backup_enabled: boolean
  backup_interval_days: number
  scan_enabled: boolean
  opencode_enabled: boolean
  cursor_enabled: boolean
  codex_enabled: boolean
  windsurf_enabled: boolean
  use_disabled_subscriptions: boolean
}

export interface BackupResult {
  path: string
  size: number
  compressed: boolean
  hash: string
}

export interface RestoreResult {
  path: string
  subscriptions_restored: number
}

export interface PaymentPeriod {
  period: string
  year: number
  month: number | null
}

export interface PaymentSummary {
  period: string
  label: string
  total: number
  subscriptions: number
  currency_breakdown: Record<string, number>
}

export interface PaymentSubItem {
  name: string
  price: number
  currency: string
  cycle: string
  billing_day: number | null
}

export interface ScanResult {
  provider: string
  found: number
  added: number
  skipped: number
  errors: string[]
}

export declare class Database {
  constructor(dbDir: string, passphrase: string | null)
  save(): void
  getSubscriptions(filter?: {
    sort?: string
    desc?: boolean
    limit?: number
    offset?: number
    includeArchived?: boolean
  }): Subscription[]
  getSubscription(id: number): Subscription | null
  addSubscription(input: NewSubscriptionInput): Subscription
  updateSubscription(id: number, input: UpdateSubscriptionInput): Subscription
  deleteSubscriptions(ids: number[]): number
  listTags(): Tag[]
  renameTag(oldName: string, newName: string): void
  deleteTag(name: string): number
  pruneTags(): number
  mergeTags(source: string, target: string): number
  addUsage(input: NewLlmUsageInput): LlmUsageEntry
  listUsage(filter: UsageFilter): LlmUsageEntry[]
  deleteUsage(ids: number[]): number
  getUsageTotal(from: string, to: string): UsageTotal
  getUsageTotalByProvider(from: string, to: string): UsageByProvider[]
  addTrial(input: NewTrialInput): TrialEntry
  listTrials(): TrialEntry[]
  getExpiringTrials(days: number): TrialEntry[]
  deleteTrials(ids: number[]): number
  getPaymentSummary(from: string, to: string): PaymentSummary
  getPaymentBreakdown(period: string | null, year: number, month: number | null): PaymentSubItem[]
  exportCsv(filePath: string, filter?: {
    tag?: string
    status?: string
  }): void
  exportJson(filePath: string, filter?: {
    tag?: string
    status?: string
  }): void
  importCsv(filePath: string): ImportResult
  backupDb(destination?: string | null): BackupResult
  restoreDb(backupPath: string): RestoreResult
  getDefaultBackupDir(): string
  getBackupFiles(dir: string): BackupFileInfo[]
  getBackupHashPath(backupPath: string): string
  writeBackupHash(backupPath: string): void
  verifyBackupHash(backupPath: string): boolean
  getDbDir(): string
  getDbPath(): string
  getConfig(): ConfigData
  updateConfig(input: Partial<ConfigData>): void
  addPriceHistory(subscriptionId: number, price: number, currency: string, cycle: string): void
  getPriceHistory(subscriptionId: number): PriceHistoryEntry[]
  addAudit(args: {
    subscription_id: number | null
    action: string
    field: string | null
    old_value: string | null
    new_value: string | null
  }): void
  getAuditLog(subscriptionId?: number | null): AuditEntry[]
  searchSubscriptions(query: string): Subscription[]
  runMaintenance(): MaintenanceResult
  optimize(): OptimizeResult
  getStats(): DatabaseStats
  execSql(sql: string, params?: string[] | null): number
}
