/* eslint-disable */
/* auto-generated by subtrack build */

const { existsSync, readFileSync } = require("fs")
const { join } = require("path")
const { platform, arch } = process

let nativeBinding = null

function isMusl() {
  if (!process.report || typeof process.report.getReport !== "function") {
    try {
      const lddPath = require("child_process")
        .execSync("which ldd")
        .toString()
        .trim()
      return readFileSync(lddPath, "utf8").includes("musl")
    } catch {
      return true
    }
  } else {
    const report = process.report.getReport()
    const sharedObjects = (report && report.sharedObjects) || []
    return sharedObjects.some(
      (s) => s.includes("libc.musl") || s.includes("ld-musl"),
    )
  }
}

switch (platform) {
  case "linux":
    switch (arch) {
      case "x64":
        nativeBinding = require("./subtrack-core.linux-x64-gnu.node")
        break
      case "arm64":
        nativeBinding = require("./subtrack-core.linux-arm64-gnu.node")
        break
    }
    break
  case "darwin":
    switch (arch) {
      case "x64":
        nativeBinding = require("./subtrack-core.darwin-x64.node")
        break
      case "arm64":
        nativeBinding = require("./subtrack-core.darwin-arm64.node")
        break
    }
    break
  case "win32":
    switch (arch) {
      case "x64":
        nativeBinding = require("./subtrack-core.win32-x64-msvc.node")
        break
      case "arm64":
        nativeBinding = require("./subtrack-core.win32-arm64-msvc.node")
        break
    }
    break
}

if (!nativeBinding) {
  throw new Error(
    `Failed to load native binding. Platform: ${platform}, arch: ${arch}`,
  )
}

module.exports = nativeBinding
